FROM python:3.12-slim

WORKDIR /app

# Instala dependências do sistema
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Instala dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código
COPY . .

# Roda migrações e popula o banco ao iniciar
CMD ["sh", "-c", "python manage.py migrate && python load.py ; python manage.py runserver 0.0.0.0:8000"]
